$class: !matrix
axis:
- $class: !text-axis
  name: OS
  valueString: 2.1 2.2
- $class: !text-axis
  name: DENSITY
  valueString: 160
- $class: !text-axis
  name: RESOLUTION
  valueString: HVGA

# Spin up an Android emulator "Build Environment" based on the
# values of our matrix build.
# NOTE: we use !key:by-name when we are in the 'key' position of
# the map.
!key:by-name Run an Android emulator during build:
  commandLineOptions: ''
  executable: ''
  deleteAfterBuild: true
  showWindow: false
  startupDelay: '0'
  useNamed:
    value: false
    avdNameSuffix: ''
    deviceLocale: ''
    osVersion: $OS
    screenDensity: $DENSITY
    screenResolution: $RESOLUTION
    sdCardSize: ''
    targetAbi: armeabi-v7a
  useSnapshots: false
  wipeData: true

builder:
  $class: !shell
  command: sleep 10