$class: !freestyle
builder:
  $class: !maven
  targets: clean verify

publisher:
  # Publish checkstyle report
  - $class: !checkstyle

  # Publish findbugs report
  - $class: !findbugs
    thresholdLimit: low
    unstableTotalAll: 0
    failedTotalAll: 0


