$class: !freestyle
properties:
  !key:by-name Parameters:
    parameterized:
      parameter:
        $class: !by-name String Parameter
        name: FOO
        defaultValue: bar
builder:
  $class: !shell
  command: echo $FOO
